### ISSUE TITLE
pretrained checkpoints

### ISSUE THREAD

**Issue by luantunez** [chvlyl/ISIC2018#10]
Hello, thank you for your work!
Would you please provide the pretrained model checkpoints for inference, please?
Thank you in advance, Lucía

**Comment by chvlyl** [comment]
Hi, thanks for your interest in my work. I provided the pretrained model weights in the README. Please read the README.

**Comment by luantunez** [comment]
Thank you for your response. Do you have a repository for your work in skin lesion classification on the ISBI 2019 challenge?
Lucia

**Comment by chvlyl** [comment]
I don't have a repo for ISBI 2019. But the method in this repo can be generalized to other similar problems.

**Comment by luantunez** [comment]
If I am getting it well this repo serves for lesion segmentation, is that right? 
Do you think it can be used (or have you implemented other models) for classification of the image into different disease classes?
